// <auto-generated />
namespace KnowIt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class secondmigrationprocedurecrud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondmigrationprocedurecrud));
        
        string IMigrationMetadata.Id
        {
            get { return "201808171427156_secondmigrationprocedurecrud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
