SET IDENTITY_INSERT [dbo].[Procedure] ON
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (1, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Left Cardiac Catheterization', N'Diagnositic procedure, coronary angio and cross the aortic valve to measure LV pressures.', N'Femoral/Radial')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (2, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Right Cardiac Catheterization', N'Measure Venous Pressures of the heart', N'Internal Jugular/Femoral')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (3, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Atrial Septal Defect Closure', N'It''s Hermiller', N'Femoral')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (4, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Temporary Pacemaker Insertion', N'Femoral/Internal Jugular', N'Due to bradycardia usually')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (5, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Debug', N'Take debugging issues to bistro to hear bistro squeeking and help concentration', N'Computer Interface')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (6, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Ventricular Septal Defect Closure', N'It''s Hermiller', N'Femoral')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (7, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Balloon Angioplasty', N'Not done very often as a standalone therapy', N'Radial/Femoral')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (8, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Laser Athrectomy', N'May be a long case', N'Femoral sometimes radially')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (9, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Rotational Athrectomy', N'Diamondback', N'Femoral')
INSERT INTO [dbo].[Procedure] ([ProcedureID], [OwnerID], [ProcedureName], [ProcedureNote], [ProcedureRoute]) VALUES (10, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Cardiomems Implant', N'Longer Right Heart Cath attempt to implant in Left PA', N'Femoral but attempting IJ')
SET IDENTITY_INSERT [dbo].[Procedure] OFF
