SET IDENTITY_INSERT [dbo].[Medication] ON
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (1, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Versed', N'Benzodiazepine', N'Sedation', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (2, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Benadryl', N'Antihistamine', N'Sedation adjunct', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (3, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Fentanyl', N'Synthetic Narcotic', N'Pain/Sedation', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (4, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Morphine', N'Narcotic', N'Pain', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (5, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Caffeine', N'Stimulant', N'Help Debugger Focus', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (6, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Dilaudid', N'Narcotic', N'Pain', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (7, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Keflex', N'Cephalosporin', N'Antibiotic', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (8, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Lidocaine', N'Sodium Channel Blocker', N'Local Anesthetic', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (9, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Epinephrine', N'Adrenergics', N'Vasopressor', 0, NULL)
INSERT INTO [dbo].[Medication] ([MedicationID], [OwnerID], [MedicationName], [MedicationClass], [MedicationUse], [Assigned], [PhysicianPreference_PhysicianPreferenceID]) VALUES (10, N'6040d91b-fd01-40c5-bcb6-37d18d6fbbf3', N'Atropine', N'Anticholenergic', N'Speed it up', 0, NULL)
SET IDENTITY_INSERT [dbo].[Medication] OFF
